os: linux
dist: trusty
sudo: required

services:
  - docker

env:
  DOCKER_VERSION: 1.12.1-0~trusty
before_install:
  - apt-cache madison docker-engine
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install --force-yes docker-engine=${DOCKER_VERSION}

script:
  - docker info
  - docker build .